### ISSUE TITLE
Pendleton Map Style Disciples Games

### ISSUE THREAD

**Issue by SpecialSundae** [nuke-haus/mapnuke#12]
Hi,

Using the Pendleton map style, with disciples enabled, with 14 nations active including 1 dominions enhanced nation (Tartary), causes an issue where the map graphics do not align with the layout of the provinces and their connections.

**Comment by nuke-haus** [comment]
Could you share the map file? curious to see what it looks like.

**Comment by Oknoye** [comment]
I can provide a map. This happened to my map too. The provinces?/connections stretch off a long way from where they are supposed to be.
[MN_6p-1w.zip](https://github.com/nuke-haus/mapnuke/files/6602510/MN_6p-1w.zip)

Here's a pic of what it looks like when I selected the province directly to the left of the capital.
![mapnuke](https://user-images.githubusercontent.com/45774753/120891219-0de7bf00-c610-11eb-8829-c9e6f48c8af2.png)

**Comment by nuke-haus** [comment]
I caught the issue. There's some bad sprites used for the water provinces in Pendleton. I'll have a fix up for this soon.
