### ISSUE TITLE
Would like to have variable sizes instead of 15 provinces per player.

### ISSUE THREAD

**Issue by ChristopherPisz** [nuke-haus/mapnuke#14]
I and many players prefer to play on a larger map, such as 20 or 25 provinces per player, so we don't have to war as soon as we want to go 2 out from cap. Would love the ability to generate a balanced map with more provinces. I see no way to tell the current version to do this.

**Comment by nuke-haus** [comment]
You can do this using the layout tool (comes bundled with the mapgen)
