### ISSUE TITLE
Generate field that doesnt correspond

### ISSUE THREAD

**Issue by WarpcGit** [nuke-haus/mapnuke#21]
Mapnuke dont auto-generate moutains, but once the map is open in dominion 5, the province is shown as a moutain.
![Proof](https://user-images.githubusercontent.com/100520451/155883905-27e5fbfc-b067-4531-9bf9-310c5574c193.jpg)
.

If the province is change manually (in mapnuke), the right image is shown.

NOTE : i use the Windows version

**Comment by nuke-haus** [comment]
If the province is touching a mountain connection it will be given the mountain flag. You can also manually set a province as a mountain province to give it the flavor sprites.
