### ISSUE TITLE
Cave nations can spawn with few neighboring provinces.

### ISSUE THREAD

**Issue by PrecociouslyDigital** [nuke-haus/mapnuke#27]
As MA Abysia my start location is a province with only 3 neighboring provinces; I suspect this is due to spawning in the cave layer; this province would have the same number of neighbors as everyone else aboveground but some of those neighbors are impassable underground.
![Screenshot 2024-04-05 at 2 04 58 PM](https://github.com/nuke-haus/mapnuke/assets/8755173/a0a02280-3810-438e-9fb4-967adfbc0c00)

**Comment by nuke-haus** [comment]
Should be addressed finally
